### ISSUE TITLE
Header image not centered on About Us page

### ISSUE THREAD

**Issue by gurdittcancode** [mlsacbvp/MLSAC-Website#114]
![image](https://github.com/mlsacbvp/MLSAC-Website/assets/93715659/a63f23d6-73f3-4c65-8e2b-48ebac56814b)

Hi, I noticed that the image on the About Us page wasn't centered and I would like to solve this issue, please assign it to me.

**Comment by Zoronium** [comment]
> Hi, I noticed that the image on the About Us page wasn't centered and I would like to solve this issue, please assign it to me.

Sure go ahead 👍
