### ISSUE TITLE
Resolving the overflow problem of home page in mobile version!

### ISSUE THREAD

**Issue by mlsacbvp** [mlsacbvp/MLSAC-Website#19]
![website_homepage](https://user-images.githubusercontent.com/92207324/136801062-9fc32b8a-7540-41ea-a3e6-9502509c4db1.jpeg)

**Comment by mohitbalwani** [comment]
Can I work on this issue?

**Comment by mlsacbvp** [comment]
@mohitbalwani okay, go ahead! But try to stay with the original design.
