### ISSUE TITLE
About Us Page Issues

### ISSUE THREAD

**Issue by divya520357** [mlsacbvp/MLSAC-Website#85]

**Comment by AK-shat-JAIN** [comment]
hey i have figred out the issue what to do next

**Comment by AK-shat-JAIN** [comment]
hollistic -> holistic

**Comment by void-ness** [comment]
Hey, It looks like you have figured out a typo on the page? can you specify the section of the page in concern too?

**Comment by AK-shat-JAIN** [comment]
its their in vis-text class

**Comment by AK-shat-JAIN** [comment]
sry in answer faq1 class

**Comment by void-ness** [comment]
As long us UI is concerned, the said typo is showing up in the faq section?

**Comment by AK-shat-JAIN** [comment]
I have fixed issue in my local cloned file

**Comment by void-ness** [comment]
have you forked the repository or just cloned it locally?

**Comment by AK-shat-JAIN** [comment]
just cloned locally

**Comment by AK-shat-JAIN** [comment]
I first forked it then cloned it in locally

**Comment by void-ness** [comment]
That sounds good. Kindly look if there are other typos on the same page. If not send a PR.

**Comment by AK-shat-JAIN** [comment]
ok Could you please tell what is PR its my first time to collaborate

**Comment by void-ness** [comment]
PR stands for Pull request. You can consider pushing your code to the forked repository and then submit a PR for review

**Comment by AK-shat-JAIN** [comment]
ok

**Comment by AK-shat-JAIN** [comment]
I Created Reques could you please verify

**Comment by void-ness** [comment]
just reviewed #90 . Have added my suggestions over there. For better clarity you can mention the PR no. in your comments just like I did in the beginning of this comment. PR no. is basically the number followed by "#" shown with you PR

**Comment by AK-shat-JAIN** [comment]
Hlo, I have corrected the issue

**Comment by void-ness** [comment]
Thank you for solving the issue. Have merged the suggestions from the PR #90 . Looking forward to seeing more contributions from you in the future :)

**Comment by AK-shat-JAIN** [comment]
Thank You for proper guidence 😊
