### ISSUE TITLE
Events Page Issues

### ISSUE THREAD

**Issue by divya520357** [mlsacbvp/MLSAC-Website#86]

**Comment by Manish-XD** [comment]
The events page looks all good, I think the only issue is some typo

**Comment by AK-shat-JAIN** [comment]
Hello, I want to solve the event page issue I found one typo there

**Comment by choudhary-vaibhav** [comment]
Sure @AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
Thank You I have Corrected the issue and created the pull request.
