### ISSUE TITLE
Updating upcoming event!

### ISSUE THREAD

**Issue by choudhary-vaibhav** [mlsacbvp/MLSAC-Website#92]

**Comment by AK-shat-JAIN** [comment]
Hello, I want to update this event page and solve the issue

**Comment by choudhary-vaibhav** [comment]
Go ahead @AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
Hello can you please guide me what to do for this

**Comment by choudhary-vaibhav** [comment]
You will have to update this write-up.
![image](https://user-images.githubusercontent.com/79092914/185174800-35844281-6733-48d6-bc7e-022368f3f465.png)

& have to enable this button with the unstop link
![image](https://user-images.githubusercontent.com/79092914/185174871-282a5161-0610-4916-91ea-41d29ec7d77d.png)

in the upcoming events section.
@AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
This written material is already there in upcoming events section

**Comment by choudhary-vaibhav** [comment]
Yeah and you have to update it...like removing the line stay tune to find more
And adding something like Do register...!

**Comment by AK-shat-JAIN** [comment]
that's ok and in Bottom link I have to give form link there

**Comment by choudhary-vaibhav** [comment]
Yeah

**Comment by AK-shat-JAIN** [comment]
ok Thanks I'll try to full fill updates asap

**Comment by AK-shat-JAIN** [comment]
I have updated and created a PR can you please review

**Comment by choudhary-vaibhav** [comment]
Merged
